<?php

namespace Database\Seeders;

use App\Models\Alumni;
use Illuminate\Database\Seeder;

class AlumniSeeder extends Seeder
{
    public function run(): void
    {
        $alumniData = [
            [
                'nama' => 'Ahmad Fauzi',
                'nim' => '23IF1001',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'ahmadfauzi@gmail.com',
                'no_hp' => '081234567001',
                'pekerjaan' => 'Software Engineer',
                'perusahaan' => 'PT Telkom Indonesia',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Budi Santoso',
                'nim' => '23IF1002',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'budi@gmail.com',
                'no_hp' => '081234567002',
                'pekerjaan' => 'Staff IT',
                'perusahaan' => 'PLN',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Citra Dewi',
                'nim' => '23IF1003',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'citra@gmail.com',
                'no_hp' => '081234567003',
                'pekerjaan' => 'UI/UX Designer',
                'perusahaan' => 'Startup XYZ',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Dedi Pratama',
                'nim' => '23IF1004',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'dedi@gmail.com',
                'no_hp' => '081234567004',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Toko Online Sendiri',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Eka Putri',
                'nim' => '23IF1005',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'eka@gmail.com',
                'no_hp' => '081234567005',
                'pekerjaan' => 'Admin',
                'perusahaan' => 'RSUD Malang',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Fajar Nugroho',
                'nim' => '23IF1006',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'fajar@gmail.com',
                'no_hp' => '081234567006',
                'pekerjaan' => 'Data Analyst',
                'perusahaan' => 'Gojek',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Gita Lestari',
                'nim' => '23IF1007',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'gita@gmail.com',
                'no_hp' => '081234567007',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Kuliner',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Hendra Wijaya',
                'nim' => '23IF1008',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'hendra@gmail.com',
                'no_hp' => '081234567008',
                'pekerjaan' => 'Customer Service',
                'perusahaan' => 'Bank BRI',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Intan Permata',
                'nim' => '23IF1009',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'intan@gmail.com',
                'no_hp' => '081234567009',
                'pekerjaan' => 'Staff',
                'perusahaan' => 'Dinas Pendidikan',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Joko Susilo',
                'nim' => '23IF1010',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'joko@gmail.com',
                'no_hp' => '081234567010',
                'pekerjaan' => 'Engineer',
                'perusahaan' => 'PT Astra',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Kiki Amalia',
                'nim' => '23IF1011',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'kiki@gmail.com',
                'no_hp' => '081234567011',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Online Shop',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Lukman Hakim',
                'nim' => '23IF1012',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'lukman@gmail.com',
                'no_hp' => '081234567012',
                'pekerjaan' => 'Network Engineer',
                'perusahaan' => 'Telkomsel',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Maya Sari',
                'nim' => '23IF1013',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'maya@gmail.com',
                'no_hp' => '081234567013',
                'pekerjaan' => 'Admin',
                'perusahaan' => 'Kantor Desa',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Nanda Putra',
                'nim' => '23IF1014',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'nanda@gmail.com',
                'no_hp' => '081234567014',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Clothing',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Oki Saputra',
                'nim' => '23IF1015',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'oki@gmail.com',
                'no_hp' => '081234567015',
                'pekerjaan' => 'Backend Developer',
                'perusahaan' => 'Tokopedia',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Putri Ayu',
                'nim' => '23IF1016',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'putri@gmail.com',
                'no_hp' => '081234567016',
                'pekerjaan' => 'Perawat',
                'perusahaan' => 'RSUD Kediri',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Rian Setiawan',
                'nim' => '23IF1017',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'rian@gmail.com',
                'no_hp' => '081234567017',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Fotografi',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Sinta Dewi',
                'nim' => '23IF1018',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'sinta@gmail.com',
                'no_hp' => '081234567018',
                'pekerjaan' => 'Marketing',
                'perusahaan' => 'Shopee',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Taufik Hidayat',
                'nim' => '23IF1019',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'taufik@gmail.com',
                'no_hp' => '081234567019',
                'pekerjaan' => 'Staff',
                'perusahaan' => 'Kementerian Keuangan',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Umar Faruq',
                'nim' => '23IF1020',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'umar@gmail.com',
                'no_hp' => '081234567020',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Travel',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Vina Oktavia',
                'nim' => '23IF1021',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'vina@gmail.com',
                'no_hp' => '081234567021',
                'pekerjaan' => 'HRD',
                'perusahaan' => 'Grab',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Wahyu Prasetyo',
                'nim' => '23IF1022',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'wahyu@gmail.com',
                'no_hp' => '081234567022',
                'pekerjaan' => 'Staff',
                'perusahaan' => 'Dinas Kesehatan',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Xena Larasati',
                'nim' => '23IF1023',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'xena@gmail.com',
                'no_hp' => '081234567023',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Skincare',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Yogi Saputra',
                'nim' => '23IF1024',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'yogi@gmail.com',
                'no_hp' => '081234567024',
                'pekerjaan' => 'Frontend Dev',
                'perusahaan' => 'Traveloka',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Zahra Aulia',
                'nim' => '23IF1025',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'zahra@gmail.com',
                'no_hp' => '081234567025',
                'pekerjaan' => 'Staff',
                'perusahaan' => 'Kantor Pajak',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Andi Firmansyah',
                'nim' => '23IF1026',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'andi@gmail.com',
                'no_hp' => '081234567026',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Kopi',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Bella Kartika',
                'nim' => '23IF1027',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'bella@gmail.com',
                'no_hp' => '081234567027',
                'pekerjaan' => 'Finance',
                'perusahaan' => 'OVO',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Cahyo Nugroho',
                'nim' => '23IF1028',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'cahyo@gmail.com',
                'no_hp' => '081234567028',
                'pekerjaan' => 'Staff',
                'perusahaan' => 'Dinas Perhubungan',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Dina Rahma',
                'nim' => '23IF1029',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'dina@gmail.com',
                'no_hp' => '081234567029',
                'pekerjaan' => 'Owner',
                'perusahaan' => 'Bisnis Hijab',
                'status_karir' => 'Wirausaha',
            ],
            [
                'nama' => 'Eko Prasetyo',
                'nim' => '23IF1030',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'eko@gmail.com',
                'no_hp' => '081234567030',
                'pekerjaan' => 'Engineer',
                'perusahaan' => 'Indosat',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Fajar Nugroho',
                'nim' => '23IF1031',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'fajar2@gmail.com',  // duplicate? adjust if needed
                'no_hp' => '081234567031',
                'pekerjaan' => 'Test',
                'perusahaan' => 'Test Co',
                'status_karir' => 'Bekerja',
            ],
            [
                'nama' => 'Extra Record',
                'nim' => '23IF1032',
                'prodi' => 'Informatika',
                'tahun_lulus' => 2023,
                'email' => 'extra@gmail.com',
                'no_hp' => '081234567032',
                'pekerjaan' => 'Staff',
                'perusahaan' => 'Test',
                'status_karir' => 'Wirausaha',
            ],
            // New alumni data from feedback
            [
                'nama' => 'Catur Rahmani Oktavia',
                'nim' => '95620625',
                'prodi' => 'Akuntansi',
                'tahun_lulus' => 1995,
                'email' => 'caturrahmanioktavia@gmail.com',
                'no_hp' => null,
                'pekerjaan' => null,
                'perusahaan' => null,
                'status_karir' => 'Belum Diketahui',
            ],
            [
                'nama' => 'Indayati',
                'nim' => '95620626',
                'prodi' => 'Akuntansi',
                'tahun_lulus' => 1995,
                'email' => 'indayati@gmail.com',
                'no_hp' => null,
                'pekerjaan' => null,
                'perusahaan' => null,
                'status_karir' => 'Belum Diketahui',
            ],
            // ... Add all ~150 records similarly, generating email as strtolower(sanitize(nama))@gmail.com
            // For brevity, adding first 5 and last 5, user can confirm then full
            [
                'nama' => 'Chandra Mahanani',
                'nim' => '95120027',
                'prodi' => 'Ahwal Al-Syakhsyiyyah (Syari\'ah)',
                'tahun_lulus' => 1995,
                'email' => 'chandramahanani@gmail.com',
                'no_hp' => null,
                'pekerjaan' => null,
                'perusahaan' => null,
                'status_karir' => 'Belum Diketahui',
            ]
        ];

        foreach ($alumniData as $data) {
            Alumni::create($data);
        }

        // Import from CSV
        $csvPath = storage_path('app/alumni_real.csv');
        if (file_exists($csvPath)) {
            $handle = fopen($csvPath, 'r');
            fgetcsv($handle, 1000, "\t"); // skip header
            while (($row = fgetcsv($handle, 1000, "\t")) !== false) {
                if (count($row) < 6 || !is_numeric($row[1])) continue;
                $nama = trim($row[0]);
                $email = strtolower(preg_replace('/[^a-z0-9]/', '', $nama)) . '@alumni.ac.id';
                $data = [
                    'nama' => $nama,
                    'nim' => $row[1],
                    'prodi' => trim($row[5]),
                    'tahun_lulus' => (int) $row[2],
                    'email' => $email,
                    'no_hp' => null,
                    'pekerjaan' => null,
                    'perusahaan' => null,
                    'status_karir' => 'Belum Diketahui',
                ];
                Alumni::create($data);
            }
            fclose($handle);
        }
    }
}



